const dummyData = {
  user: {
    userId: "helloworld",
    fullName: "Hello World",
    isUserSignedIn: false,
  },
  taskview: {
    allPendingTasksCount: 0,
    allTasks: [
      {
        taskId: "1",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 1",
        status: "pending",
        dueDateTime: "202110231500",
        scheduleDateTime: "202110231500",
        estimatedTimeOfCompletion: 2,
        colorScheme: "",
      },
      {
        taskId: "2",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 2",
        status: "completed",
        dueDateTime: "202110261500",
        scheduleDateTime: "202110011500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "3",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 3",
        status: "pending",
        dueDateTime: "202110261500",
        scheduleDateTime: "202110241500",
        estimatedTimeOfCompletion: 5,
        colorScheme: "",
      },
      {
        taskId: "4",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 4",
        status: "pending",
        dueDateTime: "202110251500",
        scheduleDateTime: "202110231500",
        estimatedTimeOfCompletion: 3,
        colorScheme: "",
      },
      {
        taskId: "5",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 5",
        status: "pending",
        dueDateTime: "202110251300",
        scheduleDateTime: "202110241300",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "6",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 6",
        status: "pending",
        dueDateTime: "202110261500",
        scheduleDateTime: "202110251500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "7",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 7",
        status: "pending",
        dueDateTime: "202110271500",
        scheduleDateTime: "202110261500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "8",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 8",
        status: "completed",
        dueDateTime: "202110281500",
        scheduleDateTime: "202110281500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "9",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 9",
        status: "pending",
        dueDateTime: "202110281500",
        scheduleDateTime: "202110281500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "10",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 10",
        status: "pending",
        dueDateTime: "202110281500",
        scheduleDateTime: "202110281500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
    ],
    allPendingTasks: [],
    selectedCommitment: null, // null will select All
    allCommitments: {
      "0": {
        commitmentId: "1",
        commitmentName: "CMPE 181",
        taskCount: 1,
        colorScheme: "#E3F18F",
      },
      "1": {
        commitmentId: "2",
        commitmentName: "CMPE 195A",
        taskCount: 2,
        colorScheme: "#8FF1AD",
      },
    },
    dashboard: {
      dueThisWeekCount: 0,
      todoASAPCount: 0,
      completedTasksCount: 0,
    },
  },
};

export default dummyData;