const dummyData = {
  user: {
    userId: "helloworld",
    fullName: "Hello World",
    isUserSignedIn: false,
  },
  taskview: {
    allPendingTasksCount: 5,
    allTasks: [
      {
        taskId: "1",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 1",
        status: "pending",
        dueDateTime: "202110231500",
        scheduleDateTime: "202110231500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "2",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 2",
        status: "completed",
        dueDateTime: "202110261500",
        scheduleDateTime: "202110011500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "3",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 3",
        status: "pending",
        dueDateTime: "202110261500",
        scheduleDateTime: "202110241500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "4",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 4",
        status: "pending",
        dueDateTime: "202110251500",
        scheduleDateTime: "202110231500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "5",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 5",
        status: "pending",
        dueDateTime: "202110251300",
        scheduleDateTime: "202110241300",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "6",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 6",
        status: "pending",
        dueDateTime: "202110261500",
        scheduleDateTime: "202110251500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "7",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 7",
        status: "pending",
        dueDateTime: "202110271500",
        scheduleDateTime: "202110261500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "8",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 8",
        status: "completed",
        dueDateTime: "202110281500",
        scheduleDateTime: "202110281500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "9",
        commitmentId: "1",
        commitmentName: "CMPE 195A",
        taskName: "Homework 9",
        status: "pending",
        dueDateTime: "202110281500",
        scheduleDateTime: "202110281500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
      {
        taskId: "10",
        commitmentId: "0",
        commitmentName: "CMPE 181",
        taskName: "Homework 10",
        status: "pending",
        dueDateTime: "202110281500",
        scheduleDateTime: "202110281500",
        estimatedTimeOfCompletion: 1,
        colorScheme: "",
      },
    ],
    allPendingTasks: [
      {
        date: "Today",
        tasks: [
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 1",
            commitmentIndex: 0,
            commitmentName: "CMPE 181",
            time: "3:00PM-4:30PM",
            dueInXDays: 0,
            colorScheme: "#E3F18F",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
        ],
      },
      {
        date: "Tomorrow",
        tasks: [
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 2",
            commitmentIndex: 1,
            commitmentName: "CMPE 195A",
            time: "3:00PM-4:30PM",
            dueInXDays: 1,
            colorScheme: "#8FF1AD",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 3",
            commitmentIndex: 1,
            commitmentName: "CMPE 195A",
            time: "3:00PM-4:30PM",
            dueInXDays: 1,
            colorScheme: "#8FF1AD",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
        ],
      },
      { date: "Friday, October 8", tasks: [] },
      { date: "Saturday, October 9", tasks: [] },
      {
        date: "Sunday, October 10",
        tasks: [
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 4",
            commitmentIndex: 0,
            commitmentName: "CMPE 181",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#E3F18F",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 5",
            commitmentIndex: 1,
            commitmentName: "CMPE 195A",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#8FF1AD",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
        ],
      },
      { date: "Monday, October 11", tasks: [] },
      { date: "Tuesday, October 12", tasks: [] },
      {
        date: "Sunday, October 10",
        tasks: [
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 4",
            commitmentIndex: 0,
            commitmentName: "CMPE 181",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#E3F18F",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 5",
            commitmentIndex: 1,
            commitmentName: "CMPE 195A",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#8FF1AD",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
        ],
      },
      {
        date: "Sunday, October 10",
        tasks: [
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 4",
            commitmentIndex: 0,
            commitmentName: "CMPE 181",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#E3F18F",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 5",
            commitmentIndex: 1,
            commitmentName: "CMPE 195A",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#8FF1AD",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
        ],
      },
      {
        date: "Sunday, October 10",
        tasks: [
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 4",
            commitmentIndex: 0,
            commitmentName: "CMPE 181",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#E3F18F",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
          {
            taskId: "",
            commitmentId: "",
            taskName: "Homework 5",
            commitmentIndex: 1,
            commitmentName: "CMPE 195A",
            time: "3:00PM-4:30PM",
            dueInXDays: 4,
            colorScheme: "#8FF1AD",
            dueDateTime: "202111011000",
            estimatedTimeOfCompletion: 1,
          },
        ],
      },
    ],
    selectedCommitment: null, // null will select All
    allCommitments: [
      {
        commitmentName: "CMPE 181",
        taskCount: 1,
        colorScheme: "#E3F18F",
      },
      {
        commitmentName: "CMPE 195A",
        taskCount: 2,
        colorScheme: "#8FF1AD",
      },
    ],
    dashboard: {
      dueThisWeekCount: 5,
      todoASAPCount: 3,
      completedTasksCount: 5,
    },
  },
};

export default dummyData;
